import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider";
import NavBar from "@/components/Navbar";
import HeroProvider from "@/components/HeroProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroProvider>

          <ReduxProvider>
            {/* <NavBar /> */}
            <div className="">
              {children}
            </div>
          </ReduxProvider>
        <Footer/>
          <Toaster />

        </HeroProvider>

      </body>
    </html>
  );
}
